name: Code Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8
    - name: Check formatting with Black
      run: black --check .
    - name: Lint with flake8
      run: flake8 .
    - name: Check import sorting with isort
      run: |
        pip install isort
        isort --check-only --diff .
